on:
  push:
    branches:
    - master
name: Deploy to Prod
jobs:
  pushToProd:
    name: Push to Prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for AWS
      uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp /github/workspace/dist/ s3://streamstats.usgs.gov/ss/
          --recursive
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@6aeb2acb39f91da283faf4c76898a723a03b2264
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: Successfully deployed to https://streamstats.usgs.gov/ss
